"""docsummary コマンドラインインターフェース。

    python -m docsummary <サブコマンド> [オプション]
    docsummary <サブコマンド> [オプション]          # venv コマンド (launcher 経由)

サブコマンド:
    run     文書を LLM で要約する (対象: ID / --dir / --pending / --all)
    list    登録文書ごとの要約状態を一覧する
    show    要約 Markdown を表示する
    config  LLM 接続設定の確認 (--check) と .env 雛形の作成 (--init)

秘密情報 (API キー) は `.env` か環境変数で渡す。このツールは値を表示・保存しない。
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from pathlib import Path
from typing import Any

from docagent.store import DocAgentError, Library, _resolve_term

from . import providers, settings as settings_mod, store as store_mod
from .settings import Settings, SettingsError
from .store import DocSummaryError, SummaryStore, UNCATEGORIZED

# LLM に渡す本文の上限文字数の既定 (env DOCSUMMARY_MAX_INPUT_CHARS で変更可)。
DEFAULT_MAX_INPUT_CHARS = 24000
# 生成側の上限トークン数の既定 (env DOCSUMMARY_MAX_OUTPUT_TOKENS で変更可)。
DEFAULT_MAX_OUTPUT_TOKENS = 4096

# LLM 応答の先頭行から付与カテゴリーを取り出すマーカー (全角/半角コロン許容)。
_CATEGORY_RE = re.compile(r"^\s*(?:カテゴリー|category)\s*[:：]\s*(.+?)\s*$",
                          re.IGNORECASE)

# 要約の出力構造はツールが固定する。LLM には「観点」と「カテゴリー分類」だけを
# 指示し、フォーマット (Markdown の見出し構造) は指定しない。
SYSTEM_PROMPT = (
    "あなたは業務文書の要約を作成する専門家である。"
    "与えられた文書の内容だけに基づいて要約し、文書に無い情報を推測で補わない。"
    "出力は次の形式に厳密に従う: 1 行目に「カテゴリー: <カテゴリー名>」を書き"
    "(必ず候補からちょうど 1 つ選ぶ)、2 行目以降に要約本文を Markdown で書く。"
    "前置き・後書き・コードフェンスは付けない。\n\n"
)


def _emit(obj: Any, as_json: bool, human) -> None:
    if as_json:
        print(json.dumps(obj, ensure_ascii=False))
    else:
        human(obj)


def _int_env(name: str, default: int) -> int:
    raw = os.environ.get(name)
    if raw is None:
        return default
    try:
        value = int(raw)
        return value if value > 0 else default
    except ValueError:
        return default


def _load_library(args: argparse.Namespace) -> Library:
    return Library.load(args.store or store_mod._paths.store_path())


def _build_prompt(guide_text: str, categories: list[str], doc: dict[str, Any],
                  body: str, truncated: bool, total_chars: int) -> tuple[str, str]:
    """(system, user) のプロンプト対を組み立てる。

    system は「観点ガイド + カテゴリー候補」を渡す (出力フォーマットは指定しない)。
    """
    system = (
        SYSTEM_PROMPT
        + "## カテゴリー候補（この中からちょうど 1 つ選ぶ）\n"
        + "、".join(categories)
        + "\n\n## 要約の観点\n" + guide_text
    )
    meta_lines = [
        f"文書名: {doc.get('source') or doc['id']}",
        f"文書種別: {doc.get('doctype') or '未分類'}",
        f"ファイル形式: {doc.get('file_type') or '不明'}",
    ]
    note = ""
    if truncated:
        note = (
            f"\n\n注意: 本文は長いため先頭部分のみ渡している"
            f" (全 {total_chars:,} 字のうち一部)。"
            "要約には「本文の一部のみを対象とした要約である」ことを明記すること。"
        )
    user = (
        "次の文書を、示された観点で日本語で要約せよ。"
        "1 行目にカテゴリー、2 行目以降に要約本文を書くこと。\n\n"
        "## 文書情報\n" + "\n".join(meta_lines) + note +
        "\n\n## 本文\n" + body
    )
    return system, user


def _split_category(raw: str, categories: list[str]) -> tuple[str, str]:
    """LLM 応答から (正規化済みカテゴリー, 本文) を取り出す。

    先頭行の「カテゴリー: …」マーカーを剥がし、値を統制語彙へ正規化する。
    語彙外・欠落は UNCATEGORIZED にフォールバックする (黙って別語彙に寄せない)。
    """
    lines = raw.split("\n")
    category = UNCATEGORIZED
    body = raw
    for i, line in enumerate(lines):
        if not line.strip():
            continue
        m = _CATEGORY_RE.match(line)
        if m:
            try:
                category = _resolve_term(m.group(1), categories, label="カテゴリー")
            except DocAgentError:
                category = UNCATEGORIZED
            body = "\n".join(lines[i + 1:]).lstrip("\n")
        break  # 先頭の非空行だけを見る
    return category, body.strip()


def _compose_summary(doc: dict[str, Any], cfg, category: str, body: str,
                     truncated: bool) -> str:
    """パース済み文書情報に要約を付加した固定構造の Markdown を組み立てる。

    見出し構造・メタ表はツールが固定し、可変部分は本文 (観点に沿った LLM 出力)
    とカテゴリー (統制語彙から付与) だけ。
    """
    meta = [
        "<!-- generated by docsummary — 手動編集は再要約で失われる -->",
        f"<!-- doc_id: {doc['id']} -->",
        f"<!-- provider: {cfg.provider} / model: {cfg.model} -->",
        f"<!-- generated_at: {store_mod._now()} -->",
    ]
    if truncated:
        meta.append("<!-- note: 本文が長いため先頭部分のみを要約 -->")
    table = [
        f"# 要約: {doc.get('source') or doc['id']}",
        "",
        "| 項目 | 内容 |",
        "| --- | --- |",
        f"| 文書種別 | {doc.get('doctype') or '未分類'} |",
        f"| カテゴリー | {category} |",
        f"| ファイル形式 | {doc.get('file_type') or '不明'} |",
    ]
    if truncated:
        table.append("| 対象範囲 | 本文の先頭部分のみ |")
    return "\n".join(meta) + "\n\n" + "\n".join(table) + "\n\n" + body + "\n"


# ── サブコマンド実装 ─────────────────────────────────────────
def cmd_run(args) -> int:
    lib = _load_library(args)
    sums = SummaryStore.load(args.summaries)
    guide_path, guide_text = store_mod.resolve_guide(args.guide_file)
    cat_path, categories = store_mod.resolve_categories(args.categories_file)
    spec = store_mod.spec_hash(guide_text, categories)

    targets = store_mod.select_targets(
        lib.documents, sums, spec,
        ids=args.targets or None, folder=args.dir,
        pending=args.pending, all_docs=args.all, force=args.force,
    )
    if not targets:
        _emit({"summarized": [], "skipped": [], "message": "対象なし (すべて要約済み)"},
              args.json, lambda o: print(o["message"]))
        return 0

    max_input = args.max_input_chars or _int_env(
        "DOCSUMMARY_MAX_INPUT_CHARS", DEFAULT_MAX_INPUT_CHARS)
    max_output = args.max_output_tokens or _int_env(
        "DOCSUMMARY_MAX_OUTPUT_TOKENS", DEFAULT_MAX_OUTPUT_TOKENS)

    if args.dry_run:
        payload = {
            "dry_run": True,
            "guide": str(guide_path),
            "categories": str(cat_path),
            "targets": [
                {"id": d["id"], "source": d.get("source"),
                 "status": sums.status_of(d, spec)}
                for d in targets
            ],
        }
        _emit(payload, args.json, lambda o: (
            print(f"対象 {len(o['targets'])} 件"
                  f" (観点: {o['guide']} / カテゴリー: {o['categories']}):"),
            [print(f"  [{t['status']:5}] {t['id']:26} {t['source']}")
             for t in o["targets"]],
        ))
        return 0

    # 接続設定は LLM 呼び出しが要るときだけ解決する (dry-run はキー不要)。
    try:
        env = Settings.load(args.env_file)
        cfg = settings_mod.resolve_config(env, args.provider, args.model)
    except SettingsError as e:
        print(f"エラー: {e}", file=sys.stderr)
        return 1

    out_dir = Path(args.out_dir) if args.out_dir else store_mod.summaries_dir()
    out_dir.mkdir(parents=True, exist_ok=True)

    done: list[dict[str, Any]] = []
    failed: list[dict[str, Any]] = []
    for doc in targets:
        try:
            text = lib.extract_text(doc["id"], max_chars=max_input)
        except DocAgentError as e:
            failed.append({"id": doc["id"], "error": str(e)})
            print(f"[NG] {doc['id']}: {e}", file=sys.stderr)
            continue
        system, user = _build_prompt(
            guide_text, categories, doc,
            text["text"], text["truncated"], text["total_chars"])
        try:
            raw = providers.complete(
                cfg, system, user, max_output_tokens=max_output,
                timeout=args.timeout,
                transport=getattr(args, "transport", None),
            )
        except providers.ProviderError as e:
            failed.append({"id": doc["id"], "error": str(e)})
            print(f"[NG] {doc['id']}: {e}", file=sys.stderr)
            continue
        category, body = _split_category(raw, categories)
        out_path = out_dir / f"{doc['id']}.md"
        out_path.write_text(
            _compose_summary(doc, cfg, category, body, text["truncated"]),
            encoding="utf-8",
        )
        entry = sums.upsert({
            "doc_id": doc["id"],
            "source": doc.get("source"),
            "category": category,
            "content_hash": doc.get("content_hash"),
            "spec_hash": spec,
            "provider": cfg.provider,
            "model": cfg.model,
            "summary_path": str(out_path).replace("\\", "/"),
            "input_chars": text["returned_chars"],
            "input_truncated": text["truncated"],
            "updated_at": store_mod._now(),
        })
        sums.save()  # 1 件ごとに保存し、途中失敗でも完了分を失わない
        done.append({"id": doc["id"], "category": category,
                     "summary_path": entry["summary_path"]})
        print(f"[OK] {doc['id']} [{category}] -> {entry['summary_path']}",
              file=sys.stderr)

    payload = {"summarized": done, "failed": failed,
               "provider": cfg.provider, "model": cfg.model}
    _emit(payload, args.json, lambda o: print(
        f"要約 {len(o['summarized'])} 件 / 失敗 {len(o['failed'])} 件"
        f" (provider={o['provider']}, model={o['model']})"
    ))
    return 1 if failed else 0


def cmd_list(args) -> int:
    lib = _load_library(args)
    sums = SummaryStore.load(args.summaries)
    _, guide_text = store_mod.resolve_guide(args.guide_file)
    _, categories = store_mod.resolve_categories(args.categories_file)
    spec = store_mod.spec_hash(guide_text, categories)
    rows = []
    for doc in lib.documents:
        status = sums.status_of(doc, spec)
        entry = sums.find(doc["id"])
        rows.append({
            "id": doc["id"],
            "source": doc.get("source"),
            "doctype": doc.get("doctype"),
            "category": entry.get("category") if entry else None,
            "status": status,
            "summary_path": entry.get("summary_path") if entry else None,
            "updated_at": entry.get("updated_at") if entry else None,
        })

    def human(o):
        print(f"登録文書 {len(o)} 件 (fresh=要約済み / stale=陳腐化 / none=未要約):")
        for r in o:
            cat = f" <{r['category']}>" if r["category"] else ""
            print(f"  [{r['status']:5}] {r['id']:26} {r['source']}{cat}")
        if not o:
            print("  (なし)")

    _emit(rows, args.json, human)
    return 0


def cmd_show(args) -> int:
    sums = SummaryStore.load(args.summaries)
    entry = sums.find(args.id)
    if entry is None:
        print(
            f"エラー: '{args.id}' の要約はまだありません。"
            f" 作成するには: docsummary run {args.id}",
            file=sys.stderr,
        )
        return 1
    path = Path(entry["summary_path"])
    if not path.is_file():
        print(
            f"エラー: 要約ファイルが見つかりません: {path}。"
            f" 再生成するには: docsummary run {args.id} --force",
            file=sys.stderr,
        )
        return 1
    if args.json:
        print(json.dumps({**entry, "text": path.read_text(encoding="utf-8-sig")},
                         ensure_ascii=False))
    else:
        print(path.read_text(encoding="utf-8-sig"))
    return 0


def cmd_config(args) -> int:
    if args.init:
        target = Path(args.path) if args.path else Path.cwd() / ".env"
        example = target.with_name(target.name + ".example")
        example.write_text(settings_mod.ENV_TEMPLATE, encoding="utf-8")
        created = [str(example)]
        if not target.exists():
            target.write_text(settings_mod.ENV_TEMPLATE, encoding="utf-8")
            created.append(str(target))
        payload = {"created": created,
                   "next": "使うプロバイダの API キーを .env に記入する"
                           " (このツールは値を読まない・表示しない)"}
        _emit(payload, args.json, lambda o: (
            [print(f"作成しました: {p}") for p in o["created"]],
            print(f"次の一手: {o['next']}"),
        ))
        return 0

    env = Settings.load(args.env_file)
    payload = settings_mod.check_payload(env, args.provider)
    guide_path, _ = store_mod.resolve_guide(args.guide_file)
    cat_path, categories = store_mod.resolve_categories(args.categories_file)
    payload["guide"] = str(guide_path)
    payload["categories_file"] = str(cat_path)
    payload["categories"] = categories

    def human(o):
        print(f".env: {o['env_file'] or '(見つからない)'}")
        print(f"要約の観点: {o['guide']}")
        print(f"カテゴリー ({o['categories_file']}): {'、'.join(o['categories'])}")
        if o["selected_provider"]:
            print(f"使用プロバイダ: {o['selected_provider']}")
        else:
            print(f"使用プロバイダ: 未決定 — {o['selection_error']}")
        for name, p in o["providers"].items():
            mark = "OK" if p["configured"] else "--"
            print(f"[{mark}] {name}")
            for v in p["vars"]:
                if v["set"]:
                    state = "設定済み (" + ("環境変数" if v["source"] == "env" else ".env") + ")"
                elif v["default"]:
                    state = f"既定値 {v['default']}"
                else:
                    state = "未設定" + (" (必須)" if v["required"] else "")
                print(f"      {v['name']:28} {state}")

    _emit(payload, args.json, human)
    return 0 if payload["selected_provider"] else 1


# ── パーサ ───────────────────────────────────────────────────
def build_parser() -> argparse.ArgumentParser:
    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("--json", action="store_true", help="機械可読な JSON で出力")
    common.add_argument("--store", help="docagent の集約 JSON (既定 <home>/store/library.json)")
    common.add_argument("--summaries", help="要約メタデータの保存先 (既定 <home>/store/summaries.json)")
    common.add_argument("--env-file", help=".env のパス (既定は cwd から上方探索)")
    common.add_argument("--provider",
                        help="LLM プロバイダ (openai / azure / gemini / anthropic)")
    common.add_argument("--guide-file", help="要約の観点ガイド Markdown のパス"
                        " (既定: <home>/store/summary_guide.md > パッケージ同梱)")
    common.add_argument("--categories-file", help="カテゴリー定義 JSON のパス"
                        " (既定: <home>/store/summary_categories.json > パッケージ同梱)")

    p = argparse.ArgumentParser(
        prog="docsummary",
        description="登録済み文書を LLM で要約する (要約フォーマット同梱)",
        parents=[common],
    )
    sub = p.add_subparsers(dest="command", required=True)

    sp = sub.add_parser("run", help="文書を要約する", parents=[common])
    sp.add_argument("targets", nargs="*", help="文書 ID (複数可。docsummary list で確認)")
    sp.add_argument("--dir", help="このフォルダ配下の元ファイルを持つ登録文書を対象にする")
    sp.add_argument("--pending", action="store_true", help="未要約・陳腐化した文書を対象にする")
    sp.add_argument("--all", action="store_true", help="全登録文書を対象にする")
    sp.add_argument("--force", action="store_true", help="要約済み (fresh) も再要約する")
    sp.add_argument("--dry-run", action="store_true",
                    help="対象一覧だけ表示して LLM は呼ばない (API キー不要)")
    sp.add_argument("--model", help="モデル名/デプロイ名の上書き")
    sp.add_argument("--max-input-chars", type=int, default=None,
                    help=f"LLM に渡す本文の上限文字数 (既定 {DEFAULT_MAX_INPUT_CHARS})")
    sp.add_argument("--max-output-tokens", type=int, default=None,
                    help=f"生成の上限トークン数 (既定 {DEFAULT_MAX_OUTPUT_TOKENS})")
    sp.add_argument("--out-dir", help="要約 Markdown の出力先 (既定 <home>/summaries)")
    sp.add_argument("--timeout", type=float, default=providers.DEFAULT_TIMEOUT,
                    help="API タイムアウト秒")
    sp.set_defaults(func=cmd_run)

    sp = sub.add_parser("list", help="登録文書ごとの要約状態を一覧", parents=[common])
    sp.set_defaults(func=cmd_list)

    sp = sub.add_parser("show", help="要約 Markdown を表示", parents=[common])
    sp.add_argument("id", help="文書 ID")
    sp.set_defaults(func=cmd_show)

    sp = sub.add_parser("config", help="接続設定の確認 (--check) / .env 雛形の作成 (--init)",
                        parents=[common])
    sp.add_argument("--check", action="store_true",
                    help="設定状態を表示する (既定の動作。値は表示しない)")
    sp.add_argument("--init", action="store_true", help=".env / .env.example の雛形を作成")
    sp.add_argument("--path", help="--init の書き出し先 .env パス (既定 カレントの .env)")
    sp.set_defaults(func=cmd_config)

    return p


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError, OSError):
            pass
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except (DocSummaryError, DocAgentError, SettingsError,
            providers.ProviderError) as e:
        print(f"エラー: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
